### ISSUE TITLE
Poggit instead of Travis?

### ISSUE THREAD

**Issue by Ad5001** [BoxOfDevs/BoxCore#3]
Travis seems to be unefficient for building phars. Should we switch to Poggit?

**Comment by Vaults1** [comment]
Maybe, but we have more control over travis.

**Comment by remotevase** [comment]
No. Travis was working fine until you destroyed it...

**Comment by Ad5001** [comment]
Not at all ! Travis has never worked on this repertory.

**Comment by remotevase** [comment]
Now it works, please do not interfere with it again.
